version: '2'
services:

  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Ahbei1de
      MYSQL_DATABASE: &mysqldb tine20
      MYSQL_USER: &mysqluser tine20
      MYSQL_PASSWORD: &mysqlpw tine20pw

  cache:
    image: redis:latest
    container_name: cache

  web:
    image: tine20:latest
    container_name: tine20
    volumes:
      # tine20 source!!!! Mount it under /tine/tine20
      - ./tine20/tine20:/tine/tine20/:ro

      # tine20 file storage!!!! Mount it under /tine/files/
      - tine20_files:/tine/files/

      # mount nginx config
      - ./configs/nginx/nginx-site.conf:/etc/nginx/sites-enabled/default.conf:ro

      # mount config
      - ./configs/tine20/:/tine/config:ro

      # tine20 tests!!!! Mount it under /tine/tests
      - ./tine20/tests/:/tine/tests/:ro

      # tine20 scripts Mount it under /tine/scripts
      - ./tine20/scripts:/tine/scripts/:ro

    ports:
      - "4000:80"      # tine
      - "4001:10443"   # webpack
    environment:
      TINE20_DBHOST: db
      TINE20_DBNAME: *mysqldb
      TINE20_DBUSER: *mysqluser
      TINE20_DBPASSWD: *mysqlpw
      TINE20_SETUPUSER: tine20setup
      TINE20_SETUPPASSWD: tine20setup
      TINE20_ADMINUSER: tine20admin
      TINE20_ADMINPASSWD: tine20admin
      TINE20_REDISHOST: cache

      # needed by PHPSTORM for debugging
      #PHP_IDE_CONFIG: "serverName=tine20docker"
      # this can be used to overwrite some xdebug config settings
      #XDEBUG_CONFIG: "remote_host=172.18.0.1 remote_enable=on remote_port=9001"
 
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    ports:
      - "4002:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Ahbei1de
      MYSQL_USER: tine20
      MYSQL_PASSWORD: tine20pw

networks:
    default:
      driver: bridge

volumes:
  # DB storage
  mariadb_data:

  # Volume for tine20 file storage
  tine20_files:
